### ISSUE TITLE
Failed at the java@0.2.9 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by d5172** [xissy/node-stanford-simple-nlp#14]
Getting lots of these sort of errors errors:
./src/java.h:23:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                         ^~~~~~~~~~~~~
                                         v8::internal::Arguments

This is on OSX Yosemite 10.10.4 with node version 0.12.7

Thanks

**Comment by HenriMeunier** [comment]
same here on linux !

**Comment by EtaySchur** [comment]
same here on linux .... just not working

**Comment by rorydonohue** [comment]
Also getting the same errors, node v0.12.6 on OSX 10.10.5.

Here is the full output. Any suggestions on how to proceed would be very welcome! 

    node-gyp rebuild
    
      CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
    In file included from ../src/java.cpp:2:
    ../src/java.h:10:27: error: expected class name
    class Java : public node::ObjectWrap {
                              ^
    ../src/java.h:23:42: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                             ^~~~~~~~~~~~~
                                             v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:24:53: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> getClassLoader(const v8::Arguments& args);
                                                        ^~~~~~~~~~~~~
                                                        v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:25:50: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> newInstance(const v8::Arguments& args);
                                                     ^~~~~~~~~~~~~
                                                     v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:26:54: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> newInstanceSync(const v8::Arguments& args);
                                                         ^~~~~~~~~~~~~
                                                         v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:27:47: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> newProxy(const v8::Arguments& args);
                                                  ^~~~~~~~~~~~~
                                                  v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:28:55: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> callStaticMethod(const v8::Arguments& args);
                                                          ^~~~~~~~~~~~~
                                                          v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:29:59: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> callStaticMethodSync(const v8::Arguments& args);
                                                              ^~~~~~~~~~~~~
                                                              v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:30:52: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> findClassSync(const v8::Arguments& args);
                                                       ^~~~~~~~~~~~~
                                                       v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:31:47: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> newArray(const v8::Arguments& args);
                                                  ^~~~~~~~~~~~~
                                                  v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:32:46: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> newByte(const v8::Arguments& args);
                                                 ^~~~~~~~~~~~~
                                                 v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:33:46: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> newChar(const v8::Arguments& args);
                                                 ^~~~~~~~~~~~~
                                                 v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:34:47: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> newShort(const v8::Arguments& args);
                                                  ^~~~~~~~~~~~~
                                                  v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:35:46: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> newLong(const v8::Arguments& args);
                                                 ^~~~~~~~~~~~~
                                                 v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:36:47: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> newFloat(const v8::Arguments& args);
                                                  ^~~~~~~~~~~~~
                                                  v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:37:48: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> newDouble(const v8::Arguments& args);
                                                   ^~~~~~~~~~~~~
                                                   v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:38:58: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> getStaticFieldValue(const v8::Arguments& args);
                                                             ^~~~~~~~~~~~~
                                                             v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:39:58: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> setStaticFieldValue(const v8::Arguments& args);
                                                             ^~~~~~~~~~~~~
                                                             v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    In file included from ../src/java.cpp:2:
    ../src/java.h:40:49: error: no type named 'Arguments' in namespace 'v8'; did you mean
          'v8::internal::Arguments'?
      static v8::Handle<v8::Value> instanceOf(const v8::Arguments& args);
                                                    ^~~~~~~~~~~~~
                                                    v8::internal::Arguments
    /Users/x/.node-gyp/0.12.6/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
          declared here
    class Arguments;
          ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    make: *** [Release/obj.target/nodejavabridge_bindings/src/java.o] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
    gyp ERR! System Darwin 14.5.0
    gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd {folder_removed}/node_modules/java
    gyp ERR! node -v v0.12.6
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok
    npm WARN ENOENT ENOENT, open '{folder_removed}/lib/package.json'
    npm ERR! Darwin 14.5.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "stanford-simple-nlp"
    npm ERR! node v0.12.6
    npm ERR! npm  v3.3.4
    npm ERR! code ELIFECYCLE
    
    npm ERR! java@0.2.9 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the java@0.2.9 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the java package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls java
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     {folder_removed}/npm-debug.log

**Comment by DenisDantsev** [comment]
Same error OSX 10.1, node v4.1.

**Comment by DenisDantsev** [comment]
You need to update java dependency version in package.json. Updating to 0.6 worked.

**Comment by withgallantry** [comment]
I'm getting this still despite changes made to package.json

**Comment by TuningGuide** [comment]
On OSX 10.11.4 I had to update the java version in package.json to 0.7.0

**Comment by c4d3r** [comment]
Works correctly with java version set to 0.7.0 (used fork to install, **npm install git+https://github.com/kareem1234/node-stanford-simple-nlp**)

**Comment by euclideansphere** [comment]
@c4d3r might be worth making a pull request with that fix?

**Comment by c4d3r** [comment]
@euclideansphere Added pull request

**Comment by Gyingguo** [comment]
update java dependency version in package.json. Updating to 0.8.0 worked.:)
