### ISSUE TITLE
Support for CoreNLP 12/09/2015 release 

### ISSUE THREAD

**Issue by buley** [xissy/node-stanford-simple-nlp#15]
`stanford-corenlp-full-2014-01-04.zip ` works great. The newest build (http://nlp.stanford.edu/software/stanford-corenlp-full-2015-12-09.zip) throws errors:

~~
Stanford CoreNLP error? { [Error: Could not find class edu.stanford.nlp.pipeline.StanfordCoreNLP
java.lang.NoClassDefFoundError: edu/stanford/nlp/pipeline/StanfordCoreNLP
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.pipeline.StanfordCoreNLP
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
] cause: {} }

**Comment by TuningGuide** [comment]
I acutally get the same error with `stanford-corenlp-full-2014-01-04` with OSX 10.11. / sync mode. Maybe I copied the contents wrongly

**Comment by vchatterji** [comment]
Take a look at https://github.com/vchatterji/stanford-ner. Might help.

**Comment by kareem1234** [comment]
Same problem over here

**Comment by Ricsie** [comment]
same problem here. any idea how to solve it? is there some new wrapper?
